Repository woowa-techcamp-2022/android-repo-06, pull requests merged in 2022-07, with the labels that each got.

#20 #7 Profile 화면 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/woowagithubrepositoryapp/App.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/profile/ProfileActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/profile/ProfileViewModel.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values/strings.xml
Labels: feature

#21 #9 네트워크 작업 코드 수정
  app/build.gradle
  app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubClient.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/network/RefreshTokenInterceptor.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/network/TokenAuthenticator.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/network/TokenInterceptor.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/network/TokenService.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/TokenRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/utils/Constants.kt
Labels: refactor

#22 #9 네트워크 issue, repository 검색
  app/src/main/java/com/example/woowagithubrepositoryapp/model/Issue.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/model/Repo.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/model/RepoOwner.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/model/RepoResponse.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/auth/LoginActivity.kt
  app/src/main/res/layout/activity_profile.xml
Labels: feature

#24 #8 유틸 - 바인딩 어댑터 추가, TimeUtil 추가
  app/build.gradle
  app/src/main/java/com/example/woowagithubrepositoryapp/utils/BindingAdapter.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/utils/TimeUtil.kt
  app/src/main/res/layout/item_notification.xml
Labels: feature

#25 #4 issue 화면 구현
  app/src/main/java/com/example/woowagithubrepositoryapp/model/Issue.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/IssueAdapter.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/SpinnerAdapter.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueViewModel.kt
  app/src/main/res/drawable/spinner_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/item_issue.xml
  app/src/main/res/layout/item_spinner.xml
  app/src/main/res/values/strings.xml
Labels: feature, wontfix

#26 #5 알림 Swipe 작업
  app/src/main/java/com/example/woowagithubrepositoryapp/model/Notification.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/model/SuccessResponse.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/NotificationAdapter.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/utils/NotificationItemHelper.kt
  app/src/main/res/layout/item_notification.xml
Labels: feature

#29 #6 Search 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/woowagithubrepositoryapp/model/Repo.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/RepositoryAdapter.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchViewModel.kt
  app/src/main/res/drawable/ic_variant10.xml
  app/src/main/res/drawable/shape_circle.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_repo.xml
Labels: feature, wontfix

#31 #3 메인 - 툴바 프로필 아이콘 작업
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
Labels: feature

#33 #32 각 프래그먼트 생성 및 초기화 패턴 수정
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
Labels: refactor

#36 #28 refactor - 코드 수정
  app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/IssueAdapter.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/auth/LoginActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchViewModel.kt
Labels: refactor

#35 #5 알림 - 페이징 처리
  app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationViewModel.kt
Labels: feature

#37 #28 refactor - ViewModelFactory 적용
  app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/network/TokenService.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/TokenRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/auth/LoginActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/auth/LoginViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/profile/ProfileActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/utils/ViewModelFactory.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_profile.xml
Labels: refactor

#40 #7 Profile - starred 정보 추가
  app/src/main/java/com/example/woowagithubrepositoryapp/model/Starred.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/model/User.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/profile/ProfileViewModel.kt
  app/src/main/res/drawable/ic_star_outline.xml
  app/src/main/res/layout/activity_profile.xml
Labels: feature

#45 #44 알림 - 목록 중복 추가 문제
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/utils/Constants.kt
Labels: bug

#46 #6 Search - 1초간 텍스트 변화 없을 시 자동 검색
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchViewModel.kt
  app/src/main/res/layout/activity_search.xml
Labels: feature

#48 #47 알림 뷰모델, 이슈 뷰모델을 메인 뷰모델로 통합
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationViewModel.kt
Labels: refactor

#49 #4 issue - filter bar 초기 background 수정
  app/src/main/res/layout/fragment_issue.xml
Labels: bug

#50 #28 refactor - 코드 개선
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/TokenRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/auth/LoginViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/utils/ActivityUtils.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/utils/ViewModelFactory.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_search.xml
Labels: refactor

#56 #42 알림 - 이전 알림 목록의 사이즈를 통해 요청을 할지 말지 결정하게 코드 수정
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
Labels: feature

#55 refactor Notification 리포지토리 - 뷰모델 Result 적용
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
Labels: refactor

#58 #51 feat 기기회전 대응 - 프로필 화면 Repositories, Starred 포함한 레이아웃 width 및 margin 수정
  app/src/main/res/layout/activity_profile.xml
Labels: feature

#61 #38 refactor 알림 - 뷰모델 viewModelScope Dispatcher 및 withContext 적용
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
Labels: refactor

#64 #62 FEAT 탭 Reselect 시 refresh 하도록 수정
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
Labels: feature

#68 #66 Refactor 네이밍 수정
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
  app/src/main/res/drawable/color_chip_rectangle_12.xml
  app/src/main/res/drawable/color_chip_rectangle_19.xml
  app/src/main/res/drawable/color_chip_rectangle_20.xml
  app/src/main/res/drawable/color_chip_rectangle_21.xml
  app/src/main/res/drawable/color_chip_rectangle_22.xml
  app/src/main/res/drawable/color_chip_rectangle_23.xml
  app/src/main/res/drawable/color_chip_rectangle_24.xml
  app/src/main/res/drawable/color_chip_rectangle_25.xml
  app/src/main/res/drawable/color_chip_rectangle_26.xml
  app/src/main/res/drawable/shape_circle.xml
  app/src/main/res/drawable/spinner_selected_background.xml
  app/src/main/res/drawable/tab_layout_selected.xml
  app/src/main/res/drawable/tab_layout_unselected.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/item_issue.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/layout/item_repo.xml
  app/src/main/res/layout/item_spinner.xml
  app/src/main/res/layout/item_spinner_default.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#71 #70 notification reselect 시 중복 호출 문제
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
Labels: bug

#76 #73 알림 async, await 이용해서 동시에 API 요청 신호 보내기
  app/src/main/java/com/example/woowagithubrepositoryapp/model/NotificationInfo.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
Labels: feature

#79 refactor 프래그먼트 전환 로직 변경
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/common/TabSelectState.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/utils/Constants.kt
Labels: refactor

#81 feat 알림 - 기기 회전 시 현재 알림 목록 크기를 이용하여 호출을 할지 말지 결정
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
Labels: feature

#88 #86 refactor - awaitAll, zip 사용하여 불필요한 리스트, 맵 삭제 및 코드 개선
  app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
Labels: refactor

#89 bug 요구사항에 맞게 fullName으로 수정
  app/src/main/res/layout/item_notification.xml
Labels: bug

#95 #94 Feat - issue, notification swipeRefreshLayout 추가
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/fragment_notification.xml
Labels: feature

#101 #28 Refactor - 알림 코드 개선
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
Labels: refactor

#102 #70 bug - API 호출 중일 때는 refresh하지않도록 처리
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
Labels: bug

#108 #107 Refactor - DataSource DI 관련 수정
  app/src/main/java/com/example/woowagithubrepositoryapp/data/datasource/GithubDataSource.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/data/datasource/GithubRemoteDataSourceImpl.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/data/repository/GithubRepository.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/data/repository/GithubRepositoryImpl.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/model/NotificationInfo.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
  app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationItemHelper.kt
Labels: refactor
